-- AlterTable
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "toEmail" TEXT;
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "ccEmails" TEXT;
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "bccEmails" TEXT;
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "replyTo" TEXT;
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "subject" TEXT;
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "attempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "EmailQueueItem" ADD COLUMN IF NOT EXISTS "lastError" TEXT;
