import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

/**
 * POST /api/invoices/renumber
 * Admin-only endpoint — reformat ALL existing invoice numbers to YYYYMM-XXXX.
 *
 * Invoices are sorted by createdAt ASC and assigned sequential numbers
 * starting at 1 using each invoice's own creation-month prefix.
 * After running, the highest existing sequence will be ≤ 0214, so the next
 * new invoice generated by nextInvoiceNumber() will be 202604-0215 or higher.
 *
 * Query params:
 *   dryRun=true   Preview only — no writes
 *
 * Example:
 *   POST /api/invoices/renumber          ← apply
 *   POST /api/invoices/renumber?dryRun=true ← preview
 */
export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Only admins
    if ((session.user as any)?.role !== 'ADMIN') {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    const dryRun = request.nextUrl.searchParams.get('dryRun') === 'true'

    // Fetch all invoices oldest-first
    const invoices = await prisma.invoice.findMany({
      select: { id: true, invoiceNumber: true, createdAt: true },
      orderBy: { createdAt: 'asc' },
    })

    if (invoices.length === 0) {
      return NextResponse.json({ message: 'No invoices found', updated: 0 })
    }

    // Build new numbers — global sequential counter, YYYYMM from each invoice's createdAt
    let seq = 0
    const updates: { id: string; oldNumber: string; newNumber: string }[] = []

    for (const inv of invoices) {
      seq++
      const d = inv.createdAt
      const prefix = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}`
      const newNumber = `${prefix}-${String(seq).padStart(4, '0')}`
      updates.push({ id: inv.id, oldNumber: inv.invoiceNumber, newNumber })
    }

    if (dryRun) {
      return NextResponse.json({
        dryRun: true,
        total: updates.length,
        lastSequence: seq,
        nextNewInvoiceWillStart: seq + 1,
        preview: updates,
      })
    }

    // Apply: two-pass to avoid unique-constraint collisions
    // Pass 1 — move all to tmp placeholders
    for (const u of updates) {
      await prisma.invoice.update({
        where: { id: u.id },
        data: { invoiceNumber: `tmp_${u.id}` },
      })
    }

    // Pass 2 — assign real new numbers
    const results: { id: string; oldNumber: string; newNumber: string }[] = []
    for (const u of updates) {
      await prisma.invoice.update({
        where: { id: u.id },
        data: { invoiceNumber: u.newNumber },
      })
      results.push(u)
    }

    return NextResponse.json({
      success: true,
      updated: results.length,
      lastSequence: seq,
      results,
    })
  } catch (err) {
    console.error('[RENUMBER INVOICES]', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
